# This file contains configuration options for Dart analysis, helping maintain code quality.
analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_return: error
    unnecessary_getters_setters: warning

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - unnecessary_new
    - lines_longer_than_80_chars: false
    - type_annotate_public_apis
    - prefer_final_fields
    - avoid_annotating_with_dynamic
    - prefer_is_empty
    - prefer_contains
    - avoid_function_literals_in_foreach_calls
    - prefer_spread_collections
    - prefer_collection_literals
    - use_key_in_widget_constructors
    - unnecessary_this
    - prefer_mixin
    - avoid_redundant_argument_values
    - prefer_typing_uninitialized_variables
    - unnecessary_null_comparison
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations